### ISSUE TITLE
Incorrect highlighting (the next line is also highlighted)

### ISSUE THREAD

**Issue by SuzanneSoy** [albfan/filter-word-diff#2]
```
git init repo
cd repo
printf 'a\nb\nc\nd\ne\nf\n' > file1
git add .
git commit -m 'initial commit'
printf 'a\nb\nc\nx\nd\ne\nf\n' > file1
git diff --word-diff=porcelain --color | filter-word-diff
```

This outputs:

```
diff --git file1 file1
index 0fdf397..ec78181 100644
--- file1
+++ file1
@@ -1,6 +1,7 @@

 a
 b
 c
+x # this line is in green
 d # this line is in green
 e
 f

```

The `d` line shouldn't be in green. Also there's an extra newline at the end after the `f`.

Using `git version 2.25.1`.

**Comment by albfan** [comment]
Thanks for look I to this

Will add a test suite so there're no regressions.

**Comment by albfan** [comment]
Lot has hmchange since I create this repo. You can pipe diff output from git internals:

http://git.dokry.com/cmo-usar-color-words-con-git-add-patch.html

**Comment by albfan** [comment]
https://github.com/git/git/tree/master/contrib/diff-highlight

The section bugs shows there're still room for improvement, but it will need human intervention

**Comment by albfan** [comment]
This should be resolved on master. Anyway there's an upstream filter that is surely a better implementation and `git diff --color-words` should do this out of the box.

The main purpose for this repo is to ignore indentation changes
